---
version: "2"
checks:
  method-complexity:
    enabled: true
    config:
      threshold: -1
plugins:
  structure:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: false # set true to check Cyclomatic Complexity
    config:
      config: .eslintrc.js
      extensions:
      - .js
